[package]
name = "imagination"
version = "0.1.0"
authors = ["Cole Lawrence <colelawr@gmail.com>"]

[dependencies]
lazy_static = "1.2.0"
quickbacktrack = "0.5.0"

[lib]
name = "manage_facts"
crate-type = ["dylib"]